import {conceptById} from './data.js';
import {templateForConcept} from './builder-templates.js';

const escapeHtml=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

const maturityGroups={protocol:new Set(['mcp','mcp-client','mcp-server','mcp-tools','mcp-resources','mcp-prompts','mcp-sampling','mcp-roots','mcp-elicitation','mcp-capability-negotiation','a2a-agent-card','a2a-tasks-messages-artifacts','ag-ui']),emerging:new Set(['harness-engineering','loop-engineering','agent-skills','progressive-disclosure','context-compaction','agent-runtime-engineering','protocol-engineering']),frontier:new Set(['long-running-agent','long-horizon-engineering','agent-drift','asynchronous-agents','generative-ui','shared-agent-ui-state','agent-containment'])};
const refs={rag:['Lewis et al. (2020), Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks.'],'agentic-rag':['Lewis et al. (2020), Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks.'],'react-pattern':['Yao et al. (2023), ReAct: Synergizing Reasoning and Acting in Language Models.'],'tool-use':['Schick et al. (2023), Toolformer: Language Models Can Teach Themselves to Use Tools.'],'tool-selection':['Schick et al. (2023), Toolformer: Language Models Can Teach Themselves to Use Tools.'],mcp:['Model Context Protocol specification and official documentation.'],'multi-agent-system':['Park et al. (2023), Generative Agents: Interactive Simulacra of Human Behavior.'],'working-memory':['Park et al. (2023), Generative Agents: Interactive Simulacra of Human Behavior.'],'prompt-injection':['OWASP guidance on prompt injection and LLM application security.'],'agent-evaluation':['Agent evaluation literature covering task success, trajectories, groundedness and robustness.'],'loop-engineering':['Agent-loop engineering literature on verification, stopping rules, budgets and recovery.'],'harness-engineering':['Production agent engineering guidance on tools, context, state, permissions and verification.']};
const currentConcept=()=>{const m=location.hash.match(/^#\/concept\/([^/?#]+)/);return m?conceptById[decodeURIComponent(m[1])]:null;};
function maturity(c){if(maturityGroups.protocol.has(c.id))return['Protocol','Defined primarily through an interoperability specification or protocol.'];if(maturityGroups.frontier.has(c.id))return['Research frontier','Active design space with open evaluation and reliability questions.'];if(maturityGroups.emerging.has(c.id))return['Emerging','Useful engineering language that is still settling across the field.'];return['Established','Widely used enough to support stable mental models and implementation patterns.'];}
function questions(c){const t=c.title,common=[`How should ${t} be measured rather than judged from one successful demo?`,`Which failure cases reveal whether ${t} is actually helping the system?`];if(c.category==='memory')return['What information should persist, expire or be retrieved just in time?',`How does ${t} change behaviour across long trajectories?`,...common];if(c.category==='tools')return['How does interface design change tool-selection reliability?','What permissions and side effects should be visible before execution?',...common];if(c.category==='human-safety')return["What should be enforced outside the model's own judgment?",'How do we bound impact when the agent is wrong?',...common];if(c.category==='evaluation')return['Which outcome and trajectory metrics best capture success?','How should offline evaluation differ from live monitoring?',...common];return[`Which part of the agent trajectory does ${t} influence?`,`What trade-off does ${t} introduce between capability, cost and reliability?`,...common];}
function metrics(c){if(c.category==='tools')return['Tool-choice accuracy','Invalid-call rate','Side-effect safety','Latency / cost'];if(c.category==='memory')return['Retrieval precision','Context utilisation','Memory contamination','Long-horizon task success'];if(c.category==='human-safety')return['Unsafe action rate','Approval precision','Blast radius','Recovery success'];if(c.category==='evaluation')return['Task success','Trajectory quality','Groundedness','Regression rate'];return['Task success','Constraint satisfaction','Trajectory length','Cost / latency'];}
function checklist(c){return[`Define the exact boundary where ${c.title} operates.`,'Make inputs, outputs and state changes observable.','Add one normal test and at least two failure tests.','Set explicit budgets, permissions or stopping rules where relevant.','Log enough of the trajectory to explain a wrong result.'];}
function refList(c){return refs[c.id]||['Russell & Norvig, Artificial Intelligence: A Modern Approach (agent foundations).','Relevant official SDK, protocol or system documentation for implementation details.'];}

export function enhanceHome(){if(location.hash&&location.hash!=='#/home')return;if(document.querySelector('.builder-teaser'))return;const anchor=document.querySelector('.living-hero');if(!anchor)return;const s=document.createElement('section');s.className='builder-teaser';s.innerHTML='<div><span class="eyebrow">WORKFLOW BUILDER</span><h2>Don’t just read about agents. Build one and break it.</h2><p>Pick a pattern such as RAG, an agent loop or human approval. Run it against tests, read the trace when it fails, then fix the design until every test passes.</p><div class="builder-flow"><span>Build</span><span>Test</span><span>Trace</span><span>Break</span><span>Fix</span></div></div><button class="primary-button" data-builder-open>Open the Workflow Builder →</button>';anchor.insertAdjacentElement('afterend',s);s.querySelector('[data-builder-open]').addEventListener('click',()=>location.hash='#/build');}
export function enhanceConcept(){const c=currentConcept();if(!c)return;const grid=document.querySelector('.lesson-heading-grid');if(!grid||document.querySelector('.concept-mode-switch'))return;const controls=document.createElement('div');controls.className='concept-mode-switch';controls.innerHTML='<button class="active" data-mode="simple">Simple</button><button data-mode="developer">Developer</button><button data-mode="research">Research</button>';grid.insertAdjacentElement('afterend',controls);controls.addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(!b)return;controls.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));renderMode(c,b.dataset.mode);});}
function renderMode(c,mode){document.querySelector('.concept-mode-panel')?.remove();if(mode==='simple')return;const lesson=document.querySelector('.lesson-content');if(!lesson)return;const p=document.createElement('section');p.className='concept-mode-panel';if(mode==='developer'){p.innerHTML=`<span class="eyebrow">DEVELOPER MODE</span><h3>Engineer ${escapeHtml(c.title)}</h3><p>Translate the concept into observable software boundaries, tests and failure handling.</p><div class="concept-mode-grid"><div class="concept-mode-card"><strong>Implementation checklist</strong><ol>${checklist(c).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ol></div><div class="concept-mode-card"><strong>Evaluate it</strong><ul>${metrics(c).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul><button class="primary-button" data-open-build="${templateForConcept(c)}">Build it in the Workflow Builder →</button></div></div>`;}else{const m=maturity(c);p.innerHTML=`<span class="eyebrow">RESEARCH MODE</span><span class="maturity-chip">${m[0]}</span><h3>Research ${escapeHtml(c.title)}</h3><p>${escapeHtml(m[1])}</p><div class="concept-mode-grid"><div class="concept-mode-card"><strong>Research questions</strong><ul>${questions(c).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div class="concept-mode-card"><strong>Evaluation methods</strong><ul>${metrics(c).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div class="concept-mode-card"><strong>Suggested references</strong><ul>${refList(c).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div class="concept-mode-card"><strong>Test it</strong><p>Change one part of the design, run the same tests again and compare. Don’t judge a design from one good output.</p><button class="primary-button" data-open-build="${templateForConcept(c)}">Build it in the Workflow Builder →</button></div></div>`;}lesson.prepend(p);p.querySelectorAll('[data-open-build]').forEach(b=>b.addEventListener('click',()=>{location.hash=`#/build/${b.dataset.openBuild}`;}));}
let scheduled=false;
function enhance(){scheduled=false;enhanceHome();enhanceConcept();}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(enhance);}
const root=document.querySelector('#app');if(root)new MutationObserver(schedule).observe(root,{childList:true,subtree:true});
window.addEventListener('hashchange',schedule);
queueMicrotask(schedule);
