export const labState={station:'observatory',observatoryStep:0,toolConfig:'clear',toolResult:null,planningConstraints:8,planningResult:null,repeatRuns:10,repeatArchitecture:'planner-verifier',repeatResult:null,failureScenario:'prompt-injection',failureFixed:false,failureResult:null,long:{budget:3000,time:8,step:0,event:null,accessibility:false,revisions:0,log:[]}};

export const stationLabels={observatory:'Agent Observatory',tools:'Tool A/B',planning:'Planning Lab',reliability:'Repeated Runs',failure:'Break the Agent',long:'Long-Horizon'};
export const stationSubtitles={observatory:'Inspect a trajectory',tools:'Test tool descriptions',planning:'Compare architectures',reliability:'Run 5–20 trials',failure:'Find unintended routes',long:'Adapt across constraints'};
export const stationDescriptions={observatory:'Open every step of an agent trajectory and connect actions to state, evidence and verification.',tools:'Test whether clearer tool contracts improve routing accuracy across a fixed benchmark.',planning:'Compare direct, ReAct, plan-then-execute and planner-plus-verifier strategies under constraints.',reliability:'Run the same agent repeatedly and measure success, groundedness, cost and worst-case behaviour.',failure:'Deliberately introduce common agent failures, inspect the trace, apply a control and run again.',long:'Operate an agent across changing budget, time and accessibility constraints while the environment changes.'};

export const escapeHtml=(v='')=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
export const seeded=input=>{let h=2166136261;for(let i=0;i<input.length;i++){h^=input.charCodeAt(i);h=Math.imul(h,16777619);}return((h>>>0)%10000)/10000;};
export const architectureLabel=id=>({direct:'Direct answer',react:'ReAct',planner:'Plan → Execute','planner-verifier':'Planner + Verifier'})[id]||id;
export const stationForConcept=concept=>{if(!concept)return'observatory';if(concept.category==='tools')return'tools';if(concept.category==='human-safety')return'failure';if(concept.category==='evaluation')return'reliability';if(concept.category==='memory')return'long';if(concept.id.includes('plan')||concept.id.includes('orchestration'))return'planning';return'observatory';};