import {labState,stationLabels,stationSubtitles,stationDescriptions} from './research-state.js';
import {stationMarkup,bindExperimentEvents} from './research-experiments.js';
import {ensureResearchNav,enhanceHome,enhanceConcept} from './research-concept-mode.js';

function topbar(){return'<header class="topbar"><button class="brand" data-lab-nav="home"><span class="brand-mark">✦</span><span>Agentic AI Master Guide</span><span class="open-badge">Research Lab</span></button><nav class="desktop-nav"><button class="nav-link" data-lab-nav="concepts">Concepts</button><button class="nav-link" data-lab-nav="paths">Learning Paths</button><button class="nav-link" data-lab-nav="playground">Playground</button><button class="nav-link is-active">Research Lab</button><a class="nav-link github-link" href="https://github.com/89Omer/agentic-ai-master-guide" target="_blank" rel="noreferrer">GitHub</a></nav><button class="mobile-menu" data-lab-nav="home">Home</button></header>';}

export function renderResearchLab(){const app=document.querySelector('#app');if(!app)return;app.innerHTML=`${topbar()}<main class="research-root" data-research-lab-root><section class="page-width research-hero"><span class="eyebrow">AGENT BEHAVIOUR LABORATORY</span><h1>Experiment with agents. Inspect what changes.</h1><p>Form a hypothesis, change one variable, run the system, inspect the trajectory, measure the result and explain the failure. Every experiment runs locally in your browser.</p><div class="research-principle"><span>Hypothesis</span><span>Variable</span><span>Repeated runs</span><span>Trajectory</span><span>Metrics</span><span>Failure analysis</span></div></section><section class="page-width"><div class="research-stations">${Object.entries(stationLabels).map(([id,label])=>`<button class="${labState.station===id?'active':''}" data-station="${id}"><strong>${label}</strong><small>${stationSubtitles[id]}</small></button>`).join('')}</div><section class="research-shell"><div class="research-shell-head"><div><span class="eyebrow">EXPERIMENT STATION</span><h2>${stationLabels[labState.station]}</h2><p>${stationDescriptions[labState.station]}</p></div><span class="research-badge">Browser simulation · no API key</span></div><div class="research-body">${stationMarkup()}</div></section></section></main><footer class="footer"><div><strong>Agentic AI Master Guide</strong><span>Understand → Experiment → Break → Evaluate → Build</span></div><div class="footer-links"><button data-lab-nav="concepts">Concepts</button><button data-lab-nav="playground">Playground</button></div></footer>`;document.querySelectorAll('[data-lab-nav]').forEach(b=>b.addEventListener('click',()=>location.hash=`#/${b.dataset.labNav}`));bindExperimentEvents(renderResearchLab);}

let scheduled=false;
function enhance(){scheduled=false;if(location.hash.startsWith('#/research-lab')){if(!document.querySelector('[data-research-lab-root]'))renderResearchLab();return;}ensureResearchNav();enhanceHome();enhanceConcept();}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(enhance);}
const root=document.querySelector('#app');if(root)new MutationObserver(schedule).observe(root,{childList:true,subtree:true});
window.addEventListener('hashchange',schedule);
queueMicrotask(schedule);